name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Client:Install dependencies
        run: cd client/ && npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build && cd ../

      - name: Server:Install dependencies
        run: cd server/ && npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
